### ISSUE TITLE
corobo security hardening 

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#509]
- [x] Make all labhub commands except invite require being a member of the org , so that corobo isnt a way around bans.
- [x] Prevent all labhub commands in private chat with the bot, optionally re-adding access for maintainers to issue labhub commands in private chat. 794be488d0fd8a7f6add1b2de040b586690124d6
- [x] Add ability to ban from all gitter rooms at once (otherwise it is very tedious) [this can be done by using api keys]
- [ ] Have corobo changes land in a staging instance before deploying to production (what keys will be different in staging?  If none, this is useless.  If some, the staging wont be testable unless labhub is connected to a different ‘dummy’ org, and then nobody will use it.)
- [x]  Prevent corobo being used to spam a room. https://github.com/coala/corobo/issues/359
- [x] Potentially remove auto-invite, replacing with developer invite https://github.com/coala/corobo/issues/322
- [x] Slow down newcomers; force them to finish one issue first https://github.com/coala/corobo/issues/184
- [x] Require newcomers to find a newcomer issue to work on before they are invited to join the org, lowing our risk profile

Created from security hardening docs created by maintainers.

**Comment by nvzard** [comment]
Make all labhub commands except invite require being a member of the org -> https://github.com/coala/corobo/commit/d697e18d436a33dca07f29e6d26544d3234750f3

Add ability to ban from all gitter rooms at once ->https://github.com/coala/corobo/commit/e24d461af968ef2bce95130c3bab12364dd962e1

Prevent corobo being used to spam a room ->https://github.com/coala/corobo/commit/fc9ba1e9e938938305b90ec6fb30361071482e0a

Potentially remove auto-invite, replacing with developer invite ->https://github.com/coala/corobo/commit/ef885b0f4b4904ef46036fe570823936440725b6

Slow down newcomers; force them to finish one issue first ->https://github.com/coala/corobo/commit/6c192f455fcd3e859d776dbef089219f7a5bd3a2

**Comment by Makman2** [comment]
A staging system is imo a separate issue and is not necessarily tied to security hardenings. Also I don't see major security benefits due to introducing a staging system, nobody really wants to do manual tests anyway so the effectiveness is rather limited. In any case, I extracted that point into a separate issue: https://github.com/coala/corobo/issues/653

Since all other points are done, closing the issue.
